import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('Hermes platform smoke runbook preserves host and voice boundaries', () {
    final text = File(
      'docs/runbooks/hermes-platform-smoke.md',
    ).readAsStringSync();

    for (final snippet in [
      '# Hermes platform smoke checklist',
      'flutter analyze',
      'flutter test --concurrency=1',
      '1016 tests',
      'flutter build web --release -t lib/main_e2e.dart',
      'flutter build apk --debug',
      'npm run hermes:readiness-audit` prints the current APK SHA-256',
      'artifact identity only, not live Android or mic evidence',
      'npm run linux:release-build',
      'Windows, iOS, and macOS builds must run on their host\nplatforms/CI runners',
      '.github/workflows/hermes-platform-smoke.yml',
      'npm run platform:workflow-smoke',
      'A local YAML file is not enough',
      'dispatch-only output is not enough',
      'workflow is now published remotely as `Hermes platform smoke`',
      'source of\ntruth is the refreshed current-head',
      'records the watched GitHub\nrun id plus successful Windows desktop',
      'Earlier local-only YAML and\nmissing-`workflow`-scope push failures are historical non-receipts',
      'latest local reprobe exited 1',
      'flutter build ios --simulator\n  --debug` exits 64',
      'Could not find an option named "--simulator"',
      'flutter build macos',
      'Could not find a subcommand named "macos" for "flutter build"',
      'successful Windows desktop, iOS simulator, and macOS desktop\nnative-host jobs/artifact metadata',
      'build/receipts/hermes-platform-workflow.json',
      'helper exits 5 and the receipt is marked failed',
      'artifact metadata, and\nnative job metadata',
      'expired, empty,\nor lacks a download URL',
      'Windows/iOS/macOS native job is not\n`completed`/`success`',
      'successful native job metadata',
      'non-expired/non-empty artifact metadata',
      '`run_status: completed`',
      'matching the receipt `head_sha` to the current git `HEAD`',
      'before treating\nWindows/iOS/macOS native-host artifacts as recorded',
      'NAVIVOX_WATCH_WORKFLOW=false',
      'only proves\ndispatch',
      'the helper exits 4 and still does not count as\na platform receipt',
      'successful Windows/iOS/macOS/Android/Linux job\nreceipts from `gh run view`',
      'NAVIVOX_FAIL_ON_BLOCKERS=1 npm run hermes:readiness-audit',
      'Completion verdict: NOT COMPLETE',
      'Do not promote proxy evidence',
      'tests,\nAPK hashes, configured Hermes home, workflow YAML, or dispatch-only output',
      'npm run hermes:live-smoke',
      'API connect/session rendering only',
      'not provider/model evidence',
      'not a chat/voice provider smoke',
      'not physical microphone evidence',
      'not\nwhole-goal completion evidence by itself',
      'strict readiness audit before any completion claim',
      'npm run hermes:provider-smoke',
      'npm run hermes:provider-smoke:local',
      'This is still transcript voice, not physical microphone or Hermes server audio,\nand not whole-goal completion evidence by itself',
      'android/live-mic-smoke.md',
      'npm run android:voice-smoke',
      'not a substitute for listening to real microphone input',
      'not whole-goal\ncompletion evidence by itself',
      'strict\nreadiness audit before any completion claim',
      'npm run android:hermes-voice-loop-smoke',
      'KVM-backed `fractal_test`',
      'deterministic Android UI loop mechanics only',
      'not a provider-backed reply receipt',
      'not\nHermes realtime/server audio, and not whole-goal completion evidence by itself',
      'still does not prove physical microphone audio input',
      'npm run android:live-mic-prep',
      'NAVIVOX_ANDROID_SKIP_BUILD=1',
      'installed/launched/granted microphone permission',
      'This prep command is not a\npass receipt and not whole-goal completion evidence by itself',
      'Legacy durable-key smoke',
      'npm run android:durable-key-smoke` remains available for preserved legacy code',
      'not part of the active pure-Hermes readiness gate',
      'Do not treat legacy\nkeypair or reconnect tests as blockers for the Hermes companion release',
    ]) {
      expect(text, contains(snippet), reason: snippet);
    }
  });
}
